### ISSUE TITLE
sendWebPush() support no payload?

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/push-encryption-node#10]
At the moment, the sendWebPush() method expects a payload and throws and error if there is no payload.

There are a few scenarios where this may not be desirable:

1.) Using existing subscription objects that dont have keys
2.) Desire to use tickles and not send payload for some messages
3.) Make it easier to drop in the library

@wibblymat thoughts on this?

Looking briefly through code, it would be a case of just checking input data and picking either sendWebPushTickle() sendWebPushWithData() OR single method (same as now), but switch between which headers are set.

@petele @paullewis @owencm thoughts on this?

**Comment by petele** [comment]
I prefer a single method, I don't have to dig through docs to figure out which one I should use, and in my code, I can pass a null/undefined value if I don't want to send anything.

**Comment by gauntface** [comment]
Yeah, sorry I meant the methods should be hidden from the user / not the
method we encourage devs to use, just an implementation detail.

But it does sound like you are pro having support for no payloads.

**Comment by petele** [comment]
Yes to pro support for no payloads... Internal implementation details, I'm less concerned about but want Devs to be able to understand it, and fork it to use for their own purposes if necessary.

**Comment by wibblymat** [comment]
Yes, sounds good, and is easy to implement. It's _almost_ just an if statement around [a few lines](https://github.com/GoogleChrome/push-encryption-node/blob/master/src/push.js#L90-L94)

**Comment by wibblymat** [comment]
What should happen if you set a message but the subscription doesn't have keys? Silently just send a tickle? Throw an error?

I'm thinking that this should throw, but open to being persuaded.

**Comment by petele** [comment]
I vote throw. If I screw up, I want to know that I screwed up, not silently fail (sending a tickle).

**Comment by gauntface** [comment]
+1 throw.

API will be:

sendWebPush(subscriptionNoKeys); // Triggers tickle
sendWebPush(subscriptionNoKeys, <String>); // Throw error
sendWebPush(subscriptionWithKeys); // Trigger tickle
sendWebPush(subscriptionWithKeys, <String>); // Send with payload
