### ISSUE TITLE
'web-push-encryption' is not in the npm registry

### ISSUE THREAD

**Issue by owencm** [GoogleChrome/push-encryption-node#20]
Weirdly I'm getting an error that this package doesn't exist in the NPM registry... Any ideas?

**Comment by ikornaselur** [comment]
While the solution would be to have the package published (or fix the readme if it's published under another name), what I've done so far was just to install it directly from Github.

```
npm install github:googlechrome/push-encryption-node --save
```

The package might change name based on #16 though, so I guess we should keep an eye out for when it's finally published into the NPM registry.

**Comment by wibblymat** [comment]
It's possible I never actually published it :s

Will check, and publish if not.

**Comment by wibblymat** [comment]
Definitely published now, sorry about that!
