### ISSUE TITLE
package.json should point to this repo in the repository field.

### ISSUE THREAD

**Issue by monteslu** [GoogleChrome/push-encryption-node#30]
I got to this repo from the readme, but if it was also in package.json it would tie the two together in the usual way.

**Comment by oldergod** [comment]
@monteslu How about a PR ?

**Comment by monteslu** [comment]
some people ask for an issue first :)

Will create PR now.

**Comment by gauntface** [comment]
+1 PR please.

**Comment by karanjthakkar** [comment]
@gauntface Since there wasn't any pending PR for this, I made one. See if it looks good :)
