### ISSUE TITLE
allow proxy setting

### ISSUE THREAD

**Issue by fbeauchamp** [GoogleChrome/push-encryption-node#33]
Hi , 
   node-gcm allows a proxy parameter, is it possible to also implement it in push-encryption ?

Regards 

Florent

**Comment by gauntface** [comment]
@fbeauchamp what would the use case be? Testing? (Sorry if thats a stupid question, but not come across node-gcm so not sure what it's for)

**Comment by ptagl** [comment]
Having a proxy setting in this module would help the deployment in scenarios where the server running it is behind a proxy.

I had a quick look at the code, and it seems like the request to the Google API uses the "request" module, and it should be really easy to allow the proxy setting.

Do you think it's possible?

Thanks!

Edit:

After searching better I've found a possible solution. The module is using "Request", and it supports environment variables, so if you run your NodeJS application like this:

HTTP_PROXY='http://myproxy.example:80' node myApp.js"

it works perfectly! :)
