### ISSUE TITLE
Java client for push encryption?

### ISSUE THREAD

**Issue by ameyakarve** [GoogleChrome/push-encryption-node#38]
I have written up a client in Java to do the push encryption. Would this be the right repository to contribute, or should it go somewhere else?

Also, is there a link to conventions, a styleguide etc. when it comes to putting in Java code?

**Comment by oldergod** [comment]
FYI Google is already working on a Java library (and a Go one). Also, there is a [Google Java Style](https://google.github.io/styleguide/javaguide.html).

**Comment by ameyakarve** [comment]
You could reuse some of my code if you wish. I have tested the outputs against this library

**Comment by ameyakarve** [comment]
It is at https://github.com/ameyakarve/gcm-chrome if it helps :-)

**Comment by jonathanpmartins** [comment]
please @oldergod, what are the chances for a full stack php lib? I have a client with a full stack php sender, and for now I am routing requests to a simple one page nodejs server that I made. Base in some codes of this lib. Nothing that cannot be control, but its like a patch or a mend for the point of view of a developer.
I know that PHP 7.1 will bring big performance for encryption algorithms. The waiting is killing me!

**Comment by mohamedhafez** [comment]
@oldergod I can't seem to find the Google Java webpush repo, is that still being developed / is there a link to the github project, or is it not on github yet? If not is there an ETA by chance? Thanks:)

**Comment by gauntface** [comment]
For everyone on this thread @ameyakarve put their code up on the web-push-libs org here: https://github.com/web-push-libs/web-push-java

If you are looking for other languages please see home page here: https://github.com/web-push-libs/
