### ISSUE TITLE
Please update docs as you change the API

### ISSUE THREAD

**Issue by RyanEwen** [GoogleChrome/push-encryption-node#43]
Hey guys,

I'd just like to request that you update the docs as you change the API. I've had it break on me a couple of times now. The latest change seems to require that we call webpush.setGCMAPIKey(apiKey) instead of passing the key in with webpush.sendWebPush().

Cheers,
Ryan

**Comment by wibblymat** [comment]
@RyanEwen you're absolutely right, that was an error on our part.

Hopefully the docs will be kept up to date in the future.
