### ISSUE TITLE
gitter chat

### ISSUE THREAD

**Issue by smkamranqadri** [GoogleChrome/push-encryption-node#45]
please create gitter chat.

**Comment by wibblymat** [comment]
Thanks for the suggestion, but I don't think it would be valuable for this project.

As a developer I already have a lot of communication channels to monitor, and I'm bad at keeping up with the ones that I use least often. I'm pretty sure that if we added Gitter here that none of the team would ever remember to use it.

If you want to discuss something with the developers about the project, please file an issue. Async discussion works much better with timezones and busy schedules.

**Comment by smkamranqadri** [comment]
i can understanding well thx.
