### ISSUE TITLE
Php client for send push and encrypt it.

### ISSUE THREAD

**Issue by jonathanpmartins** [GoogleChrome/push-encryption-node#50]
Does anyone have a plane to make a complete PHP LIB? If someone have a project, I love to help. Or if someone have the same idea do begin with, NEW, Im here. Just make in touch! 

I know that the new PHP 7.1 will come with great improvements in the cryptography algorithms! Will be great!

**Comment by Pixelarte** [comment]
yo tuve que ocupar node :S

**Comment by samthor** [comment]
It looks like there's a library here which would work for you - https://github.com/Minishlink/web-push
