### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by bradennapier** [GoogleChrome/push-encryption-node#52]
Is it not possible to get the actual status of the push ?  It says Status: 201 - Created... How would I verify the push was sent?  Every other document clearly indicates you should be lookign at the status to determine if the push was successfully sent

**Comment by samthor** [comment]
You should check the returned `Promise`.

``` js
const out = webpush.sendWebPush('hello', subscription);
out.catch(err => {
  console.warn('Failure!', err);
});
```
